### ISSUE TITLE
Incorrect package in docs?

### ISSUE THREAD

**Issue by proehlen** [Bitcoin-com/bitbox-javascript-sdk#11]
Should this be `bitbox-cli` not `bitbox`?

> To use inside a command line script or client/server app:

> `npm install bitbox --save`

https://developer.bitcoin.com/bitbox/docs/getting-started.html

The `bitbox` npm package doesn't seem to have been updated in over a year.

**Comment by proehlen** [comment]
Also, the documentation for `BITBOX.Mnemonic.validate` suggests that it returns a Boolean when the examples (and testing) suggest it always returns a string.

> Result
> valid Boolean If the mnemonic is valid

https://developer.bitcoin.com/bitbox/docs/mnemonic.html

**Comment by cgcardona** [comment]
Nice catch. Both are fixed here. 

https://github.com/Bitcoin-com/developer.bitcoin.com/commit/84b3cc3662c46aca1149c2a30c6535bcfda72dcf

Thanks

**Comment by cgcardona** [comment]
@gitcash tip $0.5 to @proehlen
