### ISSUE TITLE
Fix `rgetest` typo

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/bitbox-javascript-sdk#23]
Fix `rgetest ` typo at: https://github.com/Bitcoin-com/bitbox-javascript-sdk/blob/master/lib/Mnemonic.d.ts#L10

**Comment by haryu703** [comment]
I fixed it.
#25
Please confirm.

**Comment by cgcardona** [comment]
Fixed in v1.8.1. Thanks Yuki!

https://github.com/Bitcoin-com/bitbox-javascript-sdk/releases/tag/1.8.1
