### ISSUE TITLE
How to require bitbox-cli? 

### ISSUE THREAD

**Issue by Laccy-P** [Bitcoin-com/bitbox-javascript-sdk#32]
Please how do require this package in my app?
```` js
 require('bitbox-cli')
````
don't seem to work.

**Comment by christroutner** [comment]
Hello @Laccy-P. The BITBOX SDK was recently renamed from `bitbox-cli` to `bitbox-sdk`. Here is an example of how to instantiate BITBOX:

```
const BB = require("bitbox-sdk/lib/bitbox-sdk").default
const BITBOX = new BB({ restURL: `https://trest.bitcoin.com/v1/` })
```

That will point BITBOX as the trest testnet server. If you want your app to run on mainnet, instantiate BITBOX like this:

`const BITBOX = new BB({ restURL: `https://rest.bitcoin.com/v1/` })`

which calls rest.bitcoin.com

**Comment by Laccy-P** [comment]
Thanks @christroutner
