### ISSUE TITLE
Bitbox command line -r, --restURL tag says defaults to mainnet "rest" cloud. should be "trest"

### ISSUE THREAD

**Issue by lightswarm124** [Bitcoin-com/bitbox-javascript-sdk#40]
bitbox-javascript-sdk/index.js

line 28)

.option(
    "-r, --restURL <restURL>",
"The rest URL to use. default: https://rest.bitcoin.com/v1/" [SHOULD BE trest.bitcoin.com/v1/]

**Comment by cgcardona** [comment]
Thanks for pointing this out. It's been fixed in v2.2.1.
