### ISSUE TITLE
Add regtest documentation

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/bitbox-javascript-sdk#42]
Here is an example of Pandacash calling `BITBOX.Address.toCashAddress()` to generate a regex address. This regex functionality needs to be added to the BITBOX documentation.

https://github.com/panda-suite/pandacash-explorer/blob/efa1afd202e71a30280cab3bec3cc68bcafe3239/src/components/Account.js#L37

**Comment by cgcardona** [comment]
This is resolved here https://github.com/Bitcoin-com/developer.bitcoin.com/pull/83
