### ISSUE TITLE
Problem while requesting balance

### ISSUE THREAD

**Issue by amirzandi** [Bitcoin-com/bitbox-javascript-sdk#49]
I am using REST services and while requesting the balance, it returns 0 but the balance of my account is not 0. 

please help.

I am using /address/details url.

**Comment by amirzandi** [comment]
anyone please help.

**Comment by jcramer** [comment]
What happens when you paste in your address [here](https://rest.bitcoin.com/#/address/details)?

**Comment by amirzandi** [comment]
@jcramer thanks for your answer. Well actually it return only a 0

**Comment by amirzandi** [comment]
@jcramer https://bitref.com/1BBPF9ZoeoWXkQQp83KMM9ZQfCNcMVWAe

**Comment by dmitry-udod** [comment]
https://blockdozer.com/address/1BBPF9ZoeoWXkQQp83KMM9ZQfCNcMVWAe

**Comment by amirzandi** [comment]
@dmitry-udod the link you have mentioned shows 0, but please check this link:
https://bitref.com/1BBPF9ZoeoWXkQQp83KMM9ZQfCNcMVWAe

it shows my transactions.

**Comment by dmitry-udod** [comment]
It's the same `Final Balance: 0.00000000`
https://rest.bitcoin.com/v1/address/details/1BBPF9ZoeoWXkQQp83KMM9ZQfCNcMVWAe

**Comment by amirzandi** [comment]
@dmitry-udod my balance is not 0. you can check it at 
https://bitref.com/1BBPF9ZoeoWXkQQp83KMM9ZQfCNcMVWAe

**Comment by dmitry-udod** [comment]
You have transactions but you balance is 0
https://i.imgur.com/LTktd64.png

**Comment by amirzandi** [comment]
@dmitry-udod my mistake, please check following url:
https://bitref.com/3AXEvSM83iwFoLiUW9tGoGnHuFCRGNyb2b

**Comment by dmitry-udod** [comment]
You trying to use BCH API for `BTC`. They're different currencies. You cant get balance for Bitcoin when you using `Bitcoin Cash` API (bitbox).
https://btc.blockdozer.com/address/3AXEvSM83iwFoLiUW9tGoGnHuFCRGNyb2b

**Comment by amirzandi** [comment]
@dmitry-udod what should I use then?

**Comment by dmitry-udod** [comment]
Sorry, but I work only with BCH, try to google it :)

**Comment by amirzandi** [comment]
@dmitry-udod how can I set currency while using rest.bitcoin.com

**Comment by dmitry-udod** [comment]
I think https://rest.bitcoin.com/ only for BCH :)

**Comment by amirzandi** [comment]
thanks for your support.

**Comment by christroutner** [comment]
Closing this issue.

BTC and BCH are indeed different currencies that are incompatible with one another. BITBOX and rest.bitcoin.com only work on the BCH network.
