### ISSUE TITLE
RawTransactions.sendRawTransaction() should return a txid string when called with a single hex

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/bitbox-javascript-sdk#67]
This issue depends on [this issue in the rest repo](https://github.com/Bitcoin-com/rest.bitcoin.com/issues/273) being completed first. Once that feature change has been made to rest, BITBOX needs to be updated to reflect the same behavior:

When a single hex string is passed into `BITBOX.RawTransactions.sendRawTransactions()`, it should return a TXID as a string. The current implementation returns an array with a single string element.

**Comment by cgcardona** [comment]
Also a person should be able to pass in an array of raw hex and have it pass back an array of txids by using the newly created REST bulk sendRawTransactions endpoint

**Comment by christroutner** [comment]
This Issue will be unblocked when [this rest PR](https://github.com/Bitcoin-com/rest.bitcoin.com/pull/308/files) is merged.

**Comment by christroutner** [comment]
This issue resolved by PR #70
